#!/bin/sh
sed -i 's/"NAS"/"存储"/g' /usr/lib/lua/luci/controller/unishare.lua
sed -i 's/"NAS"/"存储"/g' /usr/lib/lua/luci/controller/quickstart.lua
sed -i 's/"NetworkGuide"/"向导"/g' /usr/lib/lua/luci/controller/quickstart.lua
sed -i 's/"S.M.A.R.T."/"硬盘状态"/g' /usr/lib/lua/luci/controller/quickstart.lua
sed -i 's/"Docker"/"容器"/g' /usr/lib/lua/luci/controller/dockerman.lua
sed -i 's#"IP/MAC Binding"#"地址绑定"#g' /usr/lib/lua/luci/controller/arpbind.lua
sed -i 's/"MosDNS"/"域名转发"/g' /usr/lib/lua/luci/controller/mosdns.lua
sed -i 's/"iStore"/"应用"/g' /usr/lib/lua/luci/controller/store.lua
sed -i 's/"OpenClash"/"世界之窗"/g' /usr/lib/lua/luci/controller/openclash.lua
sed -i 's/"KMS Server"/"微软激活"/g' /usr/lib/lua/luci/controller/vlmcsd.lua
sed -i 's/"IPTV Helper"/"电视组播"/g' /usr/lib/lua/luci/controller/iptvhelper.lua
sed -i 's/"DDNS-GO"/"域名解析"/g' /usr/lib/lua/luci/controller/ddns-go.lua
sed -i 's/"Argon Config"/"主题设置"/g' /usr/share/luci/menu.d/luci-app-argon-config.json
sed -i 's/"SmartDNS"/"域名加速"/g' /usr/share/luci/menu.d/luci-app-smartdns.json
sed -i 's#"UPnP IGD & PCP/NAT-PMP"#"即插即用"#g' /usr/share/luci/menu.d/luci-app-upnp.json
sed -i 's/"DHCP and DNS"/"动态主机"/g' /usr/share/luci/menu.d/luci-mod-network.json
sed -i 's/"Wizard"/"向导"/g' /usr/share/luci/menu.d/luci-app-wizard.json
sed -i 's/"Terminal"/"终端命令"/g' /usr/share/luci/menu.d/luci-app-ttyd.json

sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='NeoBird Compiled in $(TZ=UTC-8 date +%Y.%m.%d-%H%M) @ OpenWrt 23.05'" >> /etc/openwrt_release

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].system_chn > "/dev/null"; then
	uci -q batch <<-EOF
		set system.@system[0].timezone="CST-8"
		set system.@system[0].zonename="Asia/Shanghai"
                set system.@system[0].hostname="NeoBird"
		delete system.ntp.server
		add_list system.ntp.server="ntp.tencent.com"
		add_list system.ntp.server="ntp1.aliyun.com"
		add_list system.ntp.server="ntp.ntsc.ac.cn"
		add_list system.ntp.server="cn.ntp.org.cn"

		set system.@imm_init[0].system_chn="1"
		commit system
	EOF
fi

opkg_mirror="$(uci -q get system.@imm_init[0].opkg_mirror)"
if [ -z "$opkg_mirror" ]; then
	opkg_mirror="https://mirrors.vsean.net/openwrt"
	uci -q batch <<-EOF
		set system.@imm_init[0].opkg_mirror="$opkg_mirror"
		commit system
	EOF
fi

sed -i.bak "s,https://downloads.immortalwrt.org,$opkg_mirror,g" "/etc/opkg/distfeeds.conf"

exit 0
